theme = "edge"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
H = "goto_line_start"
L = "goto_line_end"
J = "page_down"
K = "page_up"

[keys.select]
H = "goto_line_start"
L = "goto_line_end"
J = "page_down"
K = "page_up"

